spring.application.name=security-starter
server.port=${SERVER_PORT:8080}

# DATASOURCE
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT
spring.jwt.secret=${APPLICATION_SECURITY_JWT_SECRET}
spring.jwt.access-token-expiration=${APPLICATION_SECURITY_JWT_EXPIRATION}
spring.jwt.refresh-token-expiration=${APPLICATION_SECURITY_REFRESH_TOKEN_EXPIRATION}

# SPRINGDOC
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html